version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "4000:27017"

  nodejs:
    image: vvsvipul/major1:v1.0
    container_name: nodejs
    environment:
      - DB=mongodb://mongodb:27017
      - SECRET=mysecretisthis
    ports:
      - "8080:80"
    depends_on:
      - mongodb
      - gboost
  gboost:
    image: vvsvipul/gboost:v1.0
    container_name: gboost
    ports:
      - "5000:5000"
